apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: surajmane121045/sun_frontend_app:13f98be649eeab2c506f085c96636525750e9ab9
        ports:
        - containerPort: 80

        env:
        # ConfigMap values
        - name: VITE_Backend_API_URL
          valueFrom:
            configMapKeyRef:
              name: all-config
              key: VITE_Backend_API_URL